fixtures:
  symlinks:
    "dlrn": "#{source_dir}"
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    selinux: git://github.com/spiette/puppet-selinux.git
    selinux_types: git://github.com/jgoldschrafe/puppet-selinux_types.git
    ssh: git://github.com/saz/puppet-ssh.git
    sudo: git://github.com/saz/puppet-sudo.git
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
    lvm: git://github.com/puppetlabs/puppetlabs-lvm.git
    yum: git://github.com/CERIT-SC/puppet-yum.git
    firewalld: git://github.com/crayfishx/puppet-firewalld.git
    wget: git://github.com/maestrodev/puppet-wget.git
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    letsencrypt: git@github.com:danzilio/puppet-letsencrypt.git
    inifile: git@github.com:puppetlabs/puppetlabs-inifile.git
